"""
Side-by-side Gradio demo: base Qwen2-7B-Instruct vs QLoRA fine-tuned adapter.

Given a schema and a question, shows the SQL generated by both the untouched
base model and the fine-tuned adapter, so the effect of fine-tuning is visible
at a glance.
"""

import sqlite3

import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

MODEL_ID = "Qwen/Qwen2-7B-Instruct"
ADAPTER_PATH = "./qwen2-7b-sql-qlora-final"

print("Loading model + adapter, this takes a minute...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, quantization_config=bnb_config, device_map="auto", torch_dtype=torch.float16
)
tokenizer = AutoTokenizer.from_pretrained(ADAPTER_PATH)
model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)
model.eval()
print("Loaded.")


def generate_sql(schema, question, max_new_tokens=200):
    system_msg = "You are a helpful assistant that writes SQL queries given a database schema and a question."
    user_msg = f"### Database Schema:\n{schema}\n\n### Question:\n{question}"
    messages = [
        {"role": "system", "content": system_msg},
        {"role": "user", "content": user_msg},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs, max_new_tokens=max_new_tokens, do_sample=False, pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True).strip()


def check_executes(schema, sql):
    conn = sqlite3.connect(":memory:")
    try:
        conn.executescript(schema)
        conn.execute(sql)
        return "✅ Executes successfully"
    except Exception as e:
        return f"❌ Error: {e}"
    finally:
        conn.close()


def compare_models(schema, question):
    ft_sql = generate_sql(schema, question)
    with model.disable_adapter():
        base_sql = generate_sql(schema, question)

    base_status = check_executes(schema, base_sql)
    ft_status = check_executes(schema, ft_sql)

    return base_sql, base_status, ft_sql, ft_status


demo = gr.Interface(
    fn=compare_models,
    inputs=[
        gr.Textbox(
            label="Database Schema (CREATE TABLE ...)",
            lines=4,
            placeholder="CREATE TABLE students (id INT, name TEXT, gpa FLOAT);",
        ),
        gr.Textbox(label="Question", placeholder="What is the average GPA of all students?"),
    ],
    outputs=[
        gr.Textbox(label="🔴 Base Qwen2-7B-Instruct (before fine-tuning)"),
        gr.Textbox(label="Base: executes?"),
        gr.Textbox(label="🟢 Fine-tuned Qwen2-7B (QLoRA adapter)"),
        gr.Textbox(label="Fine-tuned: executes?"),
    ],
    title="Qwen2-7B QLoRA — Text-to-SQL",
    description=(
        "Compare SQL generation before and after QLoRA fine-tuning on the "
        "Gretel synthetic text-to-SQL dataset. Same base weights, same prompt — "
        "only difference is whether the LoRA adapter is active."
    ),
    examples=[
        [
            "CREATE TABLE salesperson (salesperson_id INT, name TEXT, region TEXT);",
            "How many salespeople are in each region?",
        ],
    ],
)

if __name__ == "__main__":
    demo.launch(share=True)
